version: '2.2'
services:
  protoc:
    container_name: protoc
    build:
      context: .
      dockerfile: proto/docker/Dockerfile
    volumes:
      - ./:/workspace
    networks:
      - monorepo
    environment:
      - GRPC_PACKAGE_NAME="@grpc/grpc-js"

networks:
  monorepo:
    external: true
