version: '2.2'
services:
  api:
    container_name: go-distributed-monolith-api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - monolith
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: monolith
      MYSQL_USER: root
    networks:
      - monolith
    volumes:
      - ./docker/dev/my.cnf:/etc/mysql/conf.d/my.cnf

  dockerize:
    image: jwilder/dockerize:0.6.1
    depends_on:
      - mysql
    networks:
      - monolith
    command: dockerize

networks:
  monolith:
    external: true
