name: gotest
on: [pull_request]
jobs:
  test:
    name: runner / gotest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ./app
      - name: checkout migration
        uses: actions/checkout@v2
        with:
          repository: ispec-inc/migration
          token: ${{ secrets.REVIEWDOG_GITHUB_TOKEN }}
          path: ./migration
      - name: create docker network
        run: | 
          cd ./app
          docker network create monolith
      - name: build containers
        run: | 
          cd ./app
          cp .github/workflows/env/go-distributed-monolith .env
          cp .github/workflows/docker-compose.override.yml .
          docker-compose build
      - name: start containers
        run: |
          cd ./app
          docker-compose up -d mysql
          docker-compose run dockerize -wait tcp://mysql:3306 -timeout 20s
          docker-compose up -d api
      - name: migrate database
        run: |
          cp ./app/.github/workflows/env/migration ./migration/.env
          cd ./migration
          docker-compose up
      - name: run test
        run: |
          cd ./app
          docker-compose exec -T api go test -cover ./... -v