name: gotest

on: 
  push:
    branches:
      - master
    paths:
      - server/**
      - .github/workflows/gotest.yml
  pull_request:
    branches:
      - "*"
    paths:
      - server/** 
      - .github/workflows/gotest.yml

jobs:
  test:
    name: runner / gotest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          cp .env.default .env
          make setup
        working-directory: server
      
      - name: migration
        run: make migrate
        working-directory: server

      - name: run test
        run: make test
        working-directory: server

      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.GO_DISTRIBUTED_MONOLITH_CODECOV_TOKEN }}
          name: coverage
          flags: unittests
          fail_ci_if_error: true
          directory: server
