name: gotest
on: [push]
jobs:
  test:
    name: runner / gotest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ./app
      - name: checkout migration
        uses: actions/checkout@v2
        with:
          repository: ispec-inc/migration
          token: ${{ secrets.REVIEWDOG_GITHUB_TOKEN }}
          path: ./migration
      - name: create docker network
        run: | 
          cd ./app
          docker network create monolith
      - name: build containers
        run: | 
          cd ./app
          cp .env.default .env
          docker-compose build
      - name: start containers
        run: |
          cd ./app
          bash scripts/run.sh
      - name: migrate database
        run: |
          cd ./migration
          cp .env.default .env
          docker-compose up
      - name: run test
        run: |
          cd ./app
          docker-compose exec -T api go test ./... -v